services:
  oracle:
    image: gvenzl/oracle-xe:18-slim

    environment:
      ORACLE_PASSWORD: localtest
      APP_USER: my_user
      APP_USER_PASSWORD: localtest

    ports:
      - "1521:1521"

    volumes:
      - ./oracle/init:/container-entrypoint-initdb.d

    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
