-- Product data model: SUPPLIER, CATEGORY, PRODUCT
-- Runs once on first container start (as SYS); objects are created in MY_USER.

WHENEVER SQLERROR EXIT SQL.SQLCODE

CONNECT my_user/localtest@//localhost:1521/XEPDB1

-- ---------------------------------------------------------------------------
-- SUPPLIER
-- ---------------------------------------------------------------------------
CREATE TABLE supplier (
    supplier_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR2(150) NOT NULL,
    contact_name  VARCHAR2(150),
    email         VARCHAR2(200),
    phone         VARCHAR2(30),
    country       VARCHAR2(80),
    city          VARCHAR2(80),
    active        CHAR(1)       DEFAULT 'Y' NOT NULL,
    created_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_supplier        PRIMARY KEY (supplier_id),
    CONSTRAINT uk_supplier_name   UNIQUE (name),
    CONSTRAINT ck_supplier_active CHECK (active IN ('Y', 'N'))
);

COMMENT ON TABLE  supplier             IS 'Companies that supply products';
COMMENT ON COLUMN supplier.active      IS 'Y = active, N = inactive';

-- ---------------------------------------------------------------------------
-- CATEGORY (self-referencing hierarchy)
-- ---------------------------------------------------------------------------
CREATE TABLE category (
    category_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name                VARCHAR2(100) NOT NULL,
    description         VARCHAR2(500),
    parent_category_id  NUMBER,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_category        PRIMARY KEY (category_id),
    CONSTRAINT uk_category_name   UNIQUE (name),
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_category_id)
        REFERENCES category (category_id)
);

CREATE INDEX ix_category_parent ON category (parent_category_id);

COMMENT ON TABLE  category                    IS 'Product categories (two-level hierarchy)';
COMMENT ON COLUMN category.parent_category_id IS 'NULL for top-level categories';

-- ---------------------------------------------------------------------------
-- PRODUCT
-- ---------------------------------------------------------------------------
CREATE TABLE product (
    product_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    sku          VARCHAR2(30)   NOT NULL,
    name         VARCHAR2(200)  NOT NULL,
    description  VARCHAR2(1000),
    category_id  NUMBER         NOT NULL,
    supplier_id  NUMBER         NOT NULL,
    unit_price   NUMBER(12, 2)  NOT NULL,
    stock_qty    NUMBER(10)     DEFAULT 0 NOT NULL,
    active       CHAR(1)        DEFAULT 'Y' NOT NULL,
    created_at   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_product          PRIMARY KEY (product_id),
    CONSTRAINT uk_product_sku      UNIQUE (sku),
    CONSTRAINT fk_product_category FOREIGN KEY (category_id)
        REFERENCES category (category_id),
    CONSTRAINT fk_product_supplier FOREIGN KEY (supplier_id)
        REFERENCES supplier (supplier_id),
    CONSTRAINT ck_product_price    CHECK (unit_price >= 0),
    CONSTRAINT ck_product_stock    CHECK (stock_qty >= 0),
    CONSTRAINT ck_product_active   CHECK (active IN ('Y', 'N'))
);

CREATE INDEX ix_product_category ON product (category_id);
CREATE INDEX ix_product_supplier ON product (supplier_id);

COMMENT ON TABLE  product            IS 'Products sold, each with one category and one supplier';
COMMENT ON COLUMN product.sku        IS 'Stock keeping unit, business key';
COMMENT ON COLUMN product.unit_price IS 'Unit price in local currency';

-- ---------------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_supplier_upd
BEFORE UPDATE ON supplier FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_category_upd
BEFORE UPDATE ON category FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_product_upd
BEFORE UPDATE ON product FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/
